sources:
  - name: dagster
    description: Raw data extracted from GoCardless API by Dagster, stored in PostgreSQL
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: extracted_at
    tables:
      - name: gocardless_raw_transactions
        description: Transaction data from GoCardless API stored in PostgreSQL (gc_transactions)
        meta:
          dagster:
            asset_key:
            - source
            - gocardless
            - extract
            - transactions
      - name: gocardless_raw_account_details
        description: Account metadata and details from GoCardless API stored in PostgreSQL (gc_bank_accounts)
        meta:
          dagster:
            asset_key:
              - source
              - gocardless
              - extract
              - account_details
      - name: gocardless_raw_account_balances
        description: Balance snapshots for accounts from GoCardless API stored in PostgreSQL (gc_balances)
        meta:
          dagster:
            asset_key:
              - source
              - gocardless
              - extract
              - account_balances
