-- Loads transaction data from PostgreSQL gc_transactions table.

SELECT
    ACCOUNT_ID,
    TRANSACTION_ID,
    BOOKING_DATE,
    VALUE_DATE,
    BOOKING_DATETIME,
    TRANSACTION_AMOUNT,
    CURRENCY,
    CREDITOR_NAME,
    CREDITOR_ACCOUNT,
    DEBTOR_NAME,
    DEBTOR_ACCOUNT,
    REMITTANCE_INFORMATION,
    BANK_TRANSACTION_CODE,
    PROPRIETARY_BANK_CODE,
    STATUS,
    INTERNAL_TRANSACTION_ID,
    EXTRACTED_AT
FROM {{ source('gocardless', 'gc_transactions') }}
WHERE ACCOUNT_ID IS NOT NULL
