# Model definitions for source layer (documents output columns for lineage)
models:
  - name: src_balance_snapshots
    description: Historical balance snapshots captured at each sync for trend analysis
    columns:
      - name: id
      - name: account_id
      - name: balance_amount
      - name: balance_currency
      - name: balance_type
      - name: total_value
      - name: unrealised_pnl
      - name: source_updated_at
      - name: captured_at

  - name: src_unified_budgets
    description: Source model for monthly spending budgets from PostgreSQL
    columns:
      - name: id
      - name: user_id
      - name: tag_id
      - name: amount
      - name: currency
      - name: period
      - name: warning_threshold
      - name: enabled
      - name: created_at
      - name: updated_at

  - name: src_unified_savings_goals
    description: Source model for savings goals from PostgreSQL
    columns:
      - name: id
      - name: user_id
      - name: name
      - name: target_amount
      - name: current_amount
      - name: currency
      - name: deadline
      - name: account_id
      - name: status
      - name: notes
      - name: created_at
      - name: updated_at

  - name: src_unified_recurring_patterns
    description: Source model for recurring payment patterns from PostgreSQL
    columns:
      - name: id
      - name: user_id
      - name: merchant_pattern
      - name: account_id
      - name: expected_amount
      - name: amount_variance
      - name: currency
      - name: frequency
      - name: anchor_date
      - name: next_expected_date
      - name: last_occurrence_date
      - name: confidence_score
      - name: occurrence_count
      - name: status
      - name: display_name
      - name: notes
      - name: created_at
      - name: updated_at

  - name: src_planned_transactions
    description: Source model for planned income and expenses for forecasting
    columns:
      - name: id
      - name: user_id
      - name: name
      - name: amount
      - name: currency
      - name: frequency
      - name: next_expected_date
      - name: end_date
      - name: account_id
      - name: notes
      - name: enabled
      - name: created_at
      - name: updated_at

  - name: src_unified_accounts
    description: Unified account data from all providers
    columns:
      - name: id
      - name: connection_id
      - name: provider_id
      - name: account_type
      - name: category
      - name: credit_limit
      - name: display_name
      - name: name
      - name: iban
      - name: currency
      - name: status
      - name: last_synced_at
      - name: synced_at
      - name: balance_amount
      - name: balance_currency
      - name: balance_type
      - name: balance_updated_at
      - name: total_value
      - name: unrealised_pnl

  - name: src_unified_transaction_splits
    description: Transaction amount allocations across multiple tags
    columns:
      - name: id
      - name: transaction_id
      - name: tag_id
      - name: amount
      - name: created_at

sources:
  # Unified tables maintained by Dagster sync pipeline
  - name: unified
    description: Provider-agnostic unified tables maintained by Dagster sync pipeline
    database: pg  # PostgreSQL attached to DuckDB via postgres extension
    schema: public  # PostgreSQL public schema
    tables:
      - name: accounts
        description: Unified account data from all providers
        meta:
          dagster:
            asset_key: ["sync", "unified", "accounts"]
        columns:
          - name: id
          - name: connection_id
          - name: provider_id
          - name: account_type
          - name: category
          - name: credit_limit
          - name: display_name
          - name: name
          - name: iban
          - name: currency
          - name: status
          - name: last_synced_at
          - name: synced_at
          - name: balance_amount
          - name: balance_currency
          - name: balance_type
          - name: balance_updated_at
          - name: total_value
          - name: unrealised_pnl
      - name: connections
        description: Provider connections linking users to financial institutions
        meta:
          dagster:
            asset_key: ["sync", "unified", "connections"]
        columns:
          - name: id
          - name: user_id
          - name: institution_id
          - name: provider
          - name: provider_ref
          - name: status
          - name: last_synced_at
          - name: created_at
          - name: expires_at
      - name: institutions
        description: Financial institution metadata
        meta:
          dagster:
            asset_key: ["sync", "gocardless", "institutions"]
        columns:
          - name: id
          - name: provider
          - name: provider_id
          - name: name
          - name: logo_url
          - name: countries
      - name: transactions
        description: Unified transaction data from all providers
        meta:
          dagster:
            asset_key: ["sync", "unified", "transactions"]
        columns:
          - name: id
          - name: account_id
          - name: provider_id
          - name: booking_date
          - name: value_date
          - name: amount
          - name: currency
          - name: counterparty_name
          - name: description
          - name: category
          - name: synced_at
      - name: tags
        description: User-defined tags for categorising transactions
        columns:
          - name: id
          - name: user_id
          - name: name
          - name: colour
          - name: created_at
          - name: updated_at
      - name: transaction_splits
        description: Transaction amount allocations across multiple tags
        columns:
          - name: id
          - name: transaction_id
          - name: tag_id
          - name: amount
          - name: created_at
      - name: recurring_patterns
        description: Detected and user-confirmed recurring payment patterns
        columns:
          - name: id
          - name: user_id
          - name: merchant_pattern
          - name: account_id
          - name: expected_amount
          - name: amount_variance
          - name: currency
          - name: frequency
          - name: anchor_date
          - name: next_expected_date
          - name: last_occurrence_date
          - name: confidence_score
          - name: occurrence_count
          - name: status
          - name: display_name
          - name: notes
          - name: created_at
          - name: updated_at
      - name: budgets
        description: Monthly spending budgets per tag category
        columns:
          - name: id
          - name: user_id
          - name: tag_id
          - name: amount
          - name: currency
          - name: period
          - name: warning_threshold
          - name: enabled
          - name: created_at
          - name: updated_at
      - name: savings_goals
        description: User savings goals with optional account linking
        columns:
          - name: id
          - name: user_id
          - name: name
          - name: target_amount
          - name: current_amount
          - name: currency
          - name: deadline
          - name: account_id
          - name: status
          - name: notes
          - name: created_at
          - name: updated_at
      - name: balance_snapshots
        description: Historical balance snapshots captured at each sync
        columns:
          - name: id
          - name: account_id
          - name: balance_amount
          - name: balance_currency
          - name: balance_type
          - name: total_value
          - name: unrealised_pnl
          - name: source_updated_at
          - name: captured_at
      - name: planned_transactions
        description: User-defined planned income and expenses for forecasting
        columns:
          - name: id
          - name: user_id
          - name: name
          - name: amount
          - name: currency
          - name: frequency
          - name: next_expected_date
          - name: end_date
          - name: account_id
          - name: notes
          - name: enabled
          - name: created_at
          - name: updated_at
