sources:
  # Unified tables maintained by Dagster sync pipeline
  - name: unified
    description: Provider-agnostic unified tables maintained by Dagster sync pipeline
    database: pg  # PostgreSQL attached to DuckDB via postgres extension
    schema: public  # PostgreSQL public schema
    tables:
      - name: accounts
        description: Unified account data from all providers
        meta:
          dagster:
            asset_key: ["sync", "gocardless", "accounts"]
        columns:
          - name: id
          - name: connection_id
          - name: provider_id
          - name: account_type
          - name: display_name
          - name: name
          - name: iban
          - name: currency
          - name: status
          - name: last_synced_at
          - name: synced_at
          - name: balance_amount
          - name: balance_currency
          - name: balance_type
          - name: balance_updated_at
          - name: total_value
          - name: unrealised_pnl
      - name: connections
        description: Provider connections linking users to financial institutions
        meta:
          dagster:
            asset_key: ["sync", "gocardless", "connections"]
        columns:
          - name: id
          - name: user_id
          - name: institution_id
          - name: provider
          - name: provider_ref
          - name: status
          - name: last_synced_at
          - name: created_at
          - name: expires_at
      - name: institutions
        description: Financial institution metadata
        meta:
          dagster:
            asset_key: ["sync", "gocardless", "institutions"]
        columns:
          - name: id
          - name: provider
          - name: provider_id
          - name: name
          - name: logo_url
          - name: countries
      - name: transactions
        description: Unified transaction data from all providers
        meta:
          dagster:
            asset_key: ["sync", "gocardless", "transactions"]
        columns:
          - name: id
          - name: account_id
          - name: provider_id
          - name: booking_date
          - name: value_date
          - name: amount
          - name: currency
          - name: counterparty_name
          - name: description
          - name: category
          - name: synced_at
      - name: tags
        description: User-defined tags for categorising transactions
        columns:
          - name: id
          - name: user_id
          - name: name
          - name: colour
          - name: created_at
          - name: updated_at
      - name: transaction_splits
        description: Transaction amount allocations across multiple tags
        columns:
          - name: id
          - name: transaction_id
          - name: tag_id
          - name: amount
          - name: created_at
