sources:
  # GoCardless raw data extracted by Dagster
  # Note: These are for future work (e.g., balance history once unified).
  # Mart models should use unified sources via src_unified_* models.
  - name: gocardless
    description: Raw data extracted from GoCardless API by Dagster, stored in PostgreSQL
    database: pg  # PostgreSQL attached to DuckDB via postgres extension
    schema: public  # PostgreSQL public schema
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: extracted_at
    tables:
      - name: gc_transactions
        description: Transaction data from GoCardless API
        meta:
          dagster:
            asset_key: ["source", "gocardless", "extract", "transactions"]
        columns:
          - name: id
          - name: account_id
          - name: transaction_id
          - name: booking_date
          - name: value_date
          - name: amount
          - name: currency
          - name: counterparty_name
          - name: remittance_info
          - name: additional_info
          - name: proprietary_code
          - name: merchant_category
          - name: balance_after_transaction
          - name: extracted_at
      - name: gc_bank_accounts
        description: Account metadata and details from GoCardless API
        meta:
          dagster:
            asset_key: ["source", "gocardless", "extract", "account_details"]
        columns:
          - name: id
          - name: requisition_id
          - name: gc_account_id
          - name: iban
          - name: bban
          - name: name
          - name: product
          - name: owner_name
          - name: currency
          - name: account_type
          - name: cash_account_type
          - name: status
          - name: bic
          - name: resource_id
          - name: details
          - name: extracted_at
      - name: gc_balances
        description: Balance snapshots for accounts from GoCardless API
        meta:
          dagster:
            asset_key: ["source", "gocardless", "extract", "account_balances"]
        columns:
          - name: id
          - name: account_id
          - name: balance_amount
          - name: balance_currency
          - name: balance_type
          - name: credit_limit_included
          - name: last_change_date
          - name: last_committed_transaction
          - name: reference_date
          - name: extracted_at
