sources:
  - name: dagster
    description: Raw data extracted from GoCardless API by Dagster
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: _extract_dt
    tables:
      - name: gocardless_raw_transactions
        description: Raw transaction data from GoCardless API stored as JSON in S3
        meta:
          dagster:
            asset_key:
            - source
            - gocardless
            - extract
            - transactions
      - name: gocardless_raw_account_details
        description: Account metadata and details from GoCardless API
        meta:
          dagster:
            asset_key:
              - source
              - gocardless
              - extract
              - account_details
      - name: gocardless_raw_account_balances
        description: Balance snapshots for accounts from GoCardless API
        meta:
          dagster:
            asset_key:
              - source
              - gocardless
              - extract
              - account_balances
