"""add transaction extract date column

Revision ID: b6ce6a03986d
Revises: 9a45116053dd
Create Date: 2025-12-02 20:21:51.074743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6ce6a03986d"
down_revision: Union[str, Sequence[str], None] = "9a45116053dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gc_bank_accounts", sa.Column("dg_transaction_extract_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gc_bank_accounts", "dg_transaction_extract_date")
    # ### end Alembic commands ###
