"""add EUA table

Revision ID: fd26677b0807
Revises: b6ce6a03986d
Create Date: 2025-12-02 21:19:27.333294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd26677b0807"
down_revision: Union[str, Sequence[str], None] = "b6ce6a03986d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gc_end_user_agreements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("max_historical_days", sa.Integer(), nullable=False),
        sa.Column("access_valid_for_days", sa.Integer(), nullable=False),
        sa.Column("access_scope", sa.String(length=200), nullable=False),
        sa.Column("accepted", sa.DateTime(), nullable=True),
        sa.Column("reconfirmation", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gc_end_user_agreements")
    # ### end Alembic commands ###
