models:
  - name: dim_accounts
    description: |
      Dimension table for accounts with institution context.
      Joins accounts with connections and institutions to provide full context for analytics.
    meta:
      dataset: true
      friendly_name: "Accounts"
      group: "dimensions"
      filters:
        account_id_column: "account_id"
    columns:
      - name: account_id
        description: Unique identifier for the account (UUID)
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: Owner of the account (UUID)
        data_tests:
          - not_null
      - name: display_name
        description: User-friendly account name
        data_tests:
          - not_null
      - name: currency
        description: Primary currency of the account (ISO 4217)
      - name: account_type
        description: Type of account (bank, investment, trading)
        data_tests:
          - not_null
      - name: account_status
        description: Current status of the account (active, inactive)
        data_tests:
          - not_null
      - name: balance_amount
        description: Current balance amount
      - name: balance_currency
        description: Currency of the balance
      - name: balance_type
        description: Type of balance (expected, booked, etc.)
      - name: balance_updated_at
        description: When the balance was last updated
      - name: total_value
        description: Total value for investment accounts
      - name: unrealised_pnl
        description: Unrealised profit/loss for investment accounts
      - name: provider_id
        description: Provider-specific account identifier (for joining with provider tables)
        data_tests:
          - not_null
      - name: connection_id
        description: ID of the parent connection
        data_tests:
          - not_null
      - name: connection_name
        description: Friendly name of the connection
      - name: provider
        description: Data provider (gocardless, trading212, vanguard)
        data_tests:
          - not_null
      - name: connection_status
        description: Status of the connection
      - name: connection_expires_at
        description: When the connection expires (if applicable)
      - name: institution_id
        description: ID of the financial institution
        data_tests:
          - not_null
      - name: institution_name
        description: Name of the financial institution
      - name: institution_logo_url
        description: URL to the institution's logo

  - name: dim_tags
    description: |
      Dimension table for user-defined tags.
      Provides tag metadata for analytics joins.
    meta:
      dataset: true
      friendly_name: "Tags"
      group: "dimensions"
      filters:
        tag_id_column: "tag_id"
    columns:
      - name: tag_id
        description: Unique identifier for the tag (UUID)
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: Owner of the tag (UUID)
        data_tests:
          - not_null
      - name: name
        description: Tag name
        data_tests:
          - not_null
      - name: colour
        description: Hex colour code for the tag
      - name: created_at
        description: When the tag was created

  - name: fct_transactions
    description: |
      Fact table for transactions with tags denormalized.
      Base transaction data enriched with account and tag context for analytics.
    meta:
      dataset: true
      friendly_name: "Transactions"
      group: "facts"
      filters:
        date_column: "booking_date"
        account_id_column: "account_id"
    columns:
      - name: transaction_id
        description: Unique identifier for the transaction (UUID)
        data_tests:
          - not_null
          - unique
      - name: account_id
        description: Account the transaction belongs to (UUID)
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the account (UUID)
        data_tests:
          - not_null
      - name: booking_date
        description: Date the transaction was booked
      - name: value_date
        description: Value date of the transaction
      - name: amount
        description: Transaction amount (positive for income, negative for spending)
        data_tests:
          - not_null
      - name: currency
        description: Currency of the transaction
        data_tests:
          - not_null
      - name: counterparty_name
        description: Name of the counterparty (merchant/sender)
      - name: description
        description: Transaction description
      - name: category
        description: Transaction category
      - name: tags
        description: List of tags applied to this transaction
      - name: account_name
        description: Name of the account
      - name: institution_name
        description: Name of the financial institution
      - name: spending_amount
        description: Spending amount (positive) or 0
      - name: income_amount
        description: Income amount (positive) or 0
      - name: synced_at
        description: When the transaction was last synced

  - name: fct_daily_spending_by_tag
    description: |
      Pre-aggregated daily spending by tag.
      Aggregates transaction amounts by date and tag for efficient trend analysis.
    meta:
      dataset: true
      friendly_name: "Daily Spending by Tag"
      group: "aggregations"
      time_grain: "day"
      filters:
        date_column: "spending_date"
        tag_id_column: "tag_id"
    columns:
      - name: spending_date
        description: Date of the spending
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the transactions (UUID)
        data_tests:
          - not_null
      - name: tag_id
        description: Tag applied to the transactions (UUID)
        data_tests:
          - not_null
      - name: tag_name
        description: Name of the tag
        data_tests:
          - not_null
      - name: tag_colour
        description: Hex colour code for the tag
      - name: currency
        description: Currency of the spending
        data_tests:
          - not_null
      - name: total_spending
        description: Total spending amount for this tag on this date
        data_tests:
          - not_null
      - name: transaction_count
        description: Number of transactions
        data_tests:
          - not_null

  - name: fct_monthly_trends
    description: |
      Monthly income, spending, and net trends per user.
      Aggregates transaction data by month for high-level financial overview.
    meta:
      dataset: true
      friendly_name: "Monthly Trends"
      group: "aggregations"
      time_grain: "month"
      filters:
        date_column: "month_start"
    columns:
      - name: month_start
        description: First day of the month
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the transactions (UUID)
        data_tests:
          - not_null
      - name: currency
        description: Currency of the amounts
        data_tests:
          - not_null
      - name: total_income
        description: Total income for the month
        data_tests:
          - not_null
      - name: total_spending
        description: Total spending for the month
        data_tests:
          - not_null
      - name: net_change
        description: Net change (income - spending)
        data_tests:
          - not_null
      - name: savings_rate_pct
        description: Percentage of income saved
      - name: total_transactions
        description: Total number of transactions
        data_tests:
          - not_null
      - name: income_transactions
        description: Number of income transactions
        data_tests:
          - not_null
      - name: spending_transactions
        description: Number of spending transactions
        data_tests:
          - not_null
