models:
  - name: dim_accounts
    description: |
      Dimension table for accounts with institution context.
      Joins accounts with connections and institutions to provide full context for analytics.
    meta:
      dataset: true
      friendly_name: "Accounts"
      group: "dimensions"
      filters:
        account_id_column: "account_id"
    columns:
      - name: account_id
        description: Unique identifier for the account (UUID)
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: Owner of the account (UUID)
        data_tests:
          - not_null
      - name: display_name
        description: User-friendly account name
        data_tests:
          - not_null
      - name: currency
        description: Primary currency of the account (ISO 4217)
      - name: account_type
        description: Type of account (bank, investment, trading)
        data_tests:
          - not_null
      - name: category
        description: User-defined category (credit_card, bank_account, etc.)
      - name: credit_limit
        description: Credit limit for credit cards
      - name: account_status
        description: Current status of the account (active, inactive)
        data_tests:
          - not_null
      - name: raw_balance_amount
        description: Raw balance as reported by the bank (before normalization)
      - name: balance_amount
        description: Normalized balance (for credit cards, always represents amount owed)
      - name: balance_currency
        description: Currency of the balance
      - name: balance_type
        description: Type of balance (expected, booked, etc.)
      - name: balance_updated_at
        description: When the balance was last updated
      - name: total_value
        description: Total value for investment accounts
      - name: unrealised_pnl
        description: Unrealised profit/loss for investment accounts
      - name: provider_id
        description: Provider-specific account identifier (for joining with provider tables)
        data_tests:
          - not_null
      - name: connection_id
        description: ID of the parent connection
        data_tests:
          - not_null
      - name: connection_name
        description: Friendly name of the connection
      - name: provider
        description: Data provider (gocardless, trading212, vanguard)
        data_tests:
          - not_null
      - name: connection_status
        description: Status of the connection
      - name: connection_expires_at
        description: When the connection expires (if applicable)
      - name: institution_id
        description: ID of the financial institution
        data_tests:
          - not_null
      - name: institution_name
        description: Name of the financial institution
      - name: institution_logo_url
        description: URL to the institution's logo

  - name: dim_tags
    description: |
      Dimension table for user-defined tags.
      Provides tag metadata for analytics joins.
    meta:
      dataset: true
      friendly_name: "Tags"
      group: "dimensions"
      filters:
        tag_id_column: "tag_id"
    columns:
      - name: tag_id
        description: Unique identifier for the tag (UUID)
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: Owner of the tag (UUID)
        data_tests:
          - not_null
      - name: name
        description: Tag name
        data_tests:
          - not_null
      - name: colour
        description: Hex colour code for the tag
      - name: created_at
        description: When the tag was created

  - name: fct_transactions
    description: |
      Fact table for transactions with tags denormalized.
      Base transaction data enriched with account and tag context for analytics.
    meta:
      dataset: true
      friendly_name: "Transactions"
      group: "facts"
      filters:
        date_column: "booking_date"
        account_id_column: "account_id"
    columns:
      - name: transaction_id
        description: Unique identifier for the transaction (UUID)
        data_tests:
          - not_null
          - unique
      - name: account_id
        description: Account the transaction belongs to (UUID)
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the account (UUID)
        data_tests:
          - not_null
      - name: booking_date
        description: Date the transaction was booked
      - name: value_date
        description: Value date of the transaction
      - name: amount
        description: Transaction amount (positive for income, negative for spending)
        data_tests:
          - not_null
      - name: currency
        description: Currency of the transaction
        data_tests:
          - not_null
      - name: counterparty_name
        description: Name of the counterparty (merchant/sender)
      - name: description
        description: Transaction description
      - name: category
        description: Transaction category
      - name: tags
        description: List of tags applied to this transaction
      - name: account_name
        description: Name of the account
      - name: institution_name
        description: Name of the financial institution
      - name: spending_amount
        description: Spending amount (positive) or 0
      - name: income_amount
        description: Income amount (positive) or 0
      - name: synced_at
        description: When the transaction was last synced

  - name: fct_daily_spending_by_tag
    description: |
      Pre-aggregated daily spending by tag.
      Aggregates transaction amounts by date and tag for efficient trend analysis.
    meta:
      dataset: true
      friendly_name: "Daily Spending by Tag"
      group: "aggregations"
      time_grain: "day"
      filters:
        date_column: "spending_date"
        tag_id_column: "tag_id"
    columns:
      - name: spending_date
        description: Date of the spending
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the transactions (UUID)
        data_tests:
          - not_null
      - name: tag_id
        description: Tag applied to the transactions (UUID, null for untagged)
      - name: tag_name
        description: Name of the tag ("Untagged" for transactions without tags)
        data_tests:
          - not_null
      - name: tag_colour
        description: Hex colour code for the tag
      - name: currency
        description: Currency of the spending
        data_tests:
          - not_null
      - name: total_spending
        description: Total spending amount for this tag on this date
        data_tests:
          - not_null
      - name: transaction_count
        description: Number of transactions
        data_tests:
          - not_null

  - name: int_recurring_candidates
    description: |
      Intermediate model for recurring pattern detection.
      Analyses transaction history to identify candidate recurring payments.
    meta:
      dataset: false
      group: "intermediate"
    columns:
      - name: account_id
        description: Account the transactions belong to
      - name: user_id
        description: Owner of the account
      - name: merchant_key
        description: Normalised merchant name (lowercase, trimmed)
      - name: currency
        description: Currency of the transactions
      - name: occurrence_count
        description: Number of matching transactions
      - name: avg_amount
        description: Average transaction amount
      - name: avg_interval
        description: Average days between transactions
      - name: last_occurrence
        description: Most recent transaction date
      - name: detected_frequency
        description: Detected payment frequency (weekly, monthly, etc.)
      - name: confidence_score
        description: Pattern detection confidence (0.0-1.0)

  - name: fct_recurring_patterns
    description: |
      Fact table for recurring payment patterns (subscriptions, bills).
      Merges auto-detected patterns with user-managed patterns from the database.
    meta:
      dataset: true
      friendly_name: "Recurring Patterns"
      group: "facts"
      filters:
        date_column: "next_expected_date"
    columns:
      - name: pattern_id
        description: Unique identifier for the pattern
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the pattern
        data_tests:
          - not_null
      - name: account_id
        description: Associated account (optional)
      - name: merchant_pattern
        description: Normalised merchant name/pattern
        data_tests:
          - not_null
      - name: display_name
        description: User-friendly display name
      - name: expected_amount
        description: Expected transaction amount
        data_tests:
          - not_null
      - name: currency
        description: Currency of the amount
        data_tests:
          - not_null
      - name: frequency
        description: Payment frequency (weekly, monthly, etc.)
        data_tests:
          - not_null
      - name: status
        description: Pattern status (detected, confirmed, dismissed, paused)
        data_tests:
          - not_null
      - name: confidence_score
        description: Detection confidence (0.0-1.0)
      - name: occurrence_count
        description: Number of matched transactions
      - name: last_occurrence_date
        description: Most recent matching transaction date
      - name: next_expected_date
        description: Calculated next expected payment date
      - name: monthly_equivalent
        description: Amount converted to monthly equivalent
      - name: is_overdue
        description: Whether the pattern is past expected date + grace period
      - name: days_until_next
        description: Days until next expected payment

  - name: fct_monthly_trends
    description: |
      Monthly income, spending, and net trends per user.
      Aggregates transaction data by month for high-level financial overview.
    meta:
      dataset: true
      friendly_name: "Monthly Trends"
      group: "aggregations"
      time_grain: "month"
      filters:
        date_column: "month_start"
    columns:
      - name: month_start
        description: First day of the month
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the transactions (UUID)
        data_tests:
          - not_null
      - name: currency
        description: Currency of the amounts
        data_tests:
          - not_null
      - name: total_income
        description: Total income for the month
        data_tests:
          - not_null
      - name: total_spending
        description: Total spending for the month
        data_tests:
          - not_null
      - name: net_change
        description: Net change (income - spending)
        data_tests:
          - not_null
      - name: savings_rate_pct
        description: Percentage of income saved
      - name: total_transactions
        description: Total number of transactions
        data_tests:
          - not_null
      - name: income_transactions
        description: Number of income transactions
        data_tests:
          - not_null
      - name: spending_transactions
        description: Number of spending transactions
        data_tests:
          - not_null

  - name: fct_budget_vs_actual
    description: |
      Budget vs actual spending comparison for the current month.
      Compares monthly budgets against actual spending by tag category.
    meta:
      dataset: true
      friendly_name: "Budget vs Actual"
      group: "budgets"
      filters:
        tag_id_column: "tag_id"
    columns:
      - name: budget_id
        description: Budget UUID
        data_tests:
          - not_null
      - name: user_id
        description: Owner of the budget (UUID)
        data_tests:
          - not_null
      - name: tag_id
        description: Tag UUID for budget category
        data_tests:
          - not_null
      - name: tag_name
        description: Tag name
        data_tests:
          - not_null
      - name: tag_colour
        description: Tag colour (hex)
      - name: budget_amount
        description: Monthly budget limit
        data_tests:
          - not_null
      - name: currency
        description: Currency code
        data_tests:
          - not_null
      - name: warning_threshold
        description: Warning threshold (0.0-1.0)
      - name: spent_amount
        description: Amount spent in current period
        data_tests:
          - not_null
      - name: transaction_count
        description: Number of transactions
        data_tests:
          - not_null
      - name: remaining_amount
        description: Remaining budget
        data_tests:
          - not_null
      - name: percentage_used
        description: Percentage of budget used
        data_tests:
          - not_null
      - name: budget_status
        description: Status - ok, warning, or exceeded
        data_tests:
          - not_null
      - name: period_start
        description: Start of budget period
        data_tests:
          - not_null
      - name: period_end
        description: End of budget period
        data_tests:
          - not_null
      - name: period_key
        description: Period key (YYYY-MM)
        data_tests:
          - not_null

  - name: fct_goal_progress
    description: |
      Savings goal progress tracking.
      Includes calculated metrics for progress, remaining amount, and deadline tracking.
    meta:
      dataset: true
      friendly_name: "Goal Progress"
      group: "goals"
    columns:
      - name: goal_id
        description: Goal UUID
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: Owner of the goal (UUID)
        data_tests:
          - not_null
      - name: goal_name
        description: Goal name
        data_tests:
          - not_null
      - name: target_amount
        description: Target savings amount
        data_tests:
          - not_null
      - name: current_amount
        description: Current saved amount (from manual entry or linked account)
        data_tests:
          - not_null
      - name: currency
        description: Currency code
        data_tests:
          - not_null
      - name: deadline
        description: Target deadline
      - name: account_id
        description: Linked account UUID (if auto-tracking)
      - name: account_name
        description: Linked account name
      - name: status
        description: Goal status (active, paused, completed, cancelled)
        data_tests:
          - not_null
      - name: notes
        description: User notes
      - name: progress_percentage
        description: Progress percentage (0-100)
        data_tests:
          - not_null
      - name: remaining_amount
        description: Amount remaining to reach target
        data_tests:
          - not_null
      - name: days_remaining
        description: Days until deadline (null if no deadline)
      - name: is_overdue
        description: Whether goal is past deadline
      - name: is_on_track
        description: Whether current progress rate will reach target by deadline
      - name: created_at
        description: When goal was created
        data_tests:
          - not_null
      - name: updated_at
        description: When goal was last updated
        data_tests:
          - not_null
