"""add_trading212_history_tables

Revision ID: 0a6594cba516
Revises: e1f2a3b4c5d6
Create Date: 2026-01-28 22:32:35.121053

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6594cba516'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t212_dividends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('t212_reference', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('instrument_name', sa.String(length=256), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount_in_euro', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_amount_per_share', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('dividend_type', sa.String(length=32), nullable=True),
    sa.Column('paid_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['t212_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_t212_dividends_api_key_id', 't212_dividends', ['api_key_id'], unique=False)
    op.create_index('idx_t212_dividends_paid_on', 't212_dividends', ['paid_on'], unique=False)
    op.create_index('idx_t212_dividends_t212_reference', 't212_dividends', ['t212_reference'], unique=False)
    op.create_index('idx_t212_dividends_ticker', 't212_dividends', ['ticker'], unique=False)
    op.create_table('t212_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('t212_order_id', sa.String(length=64), nullable=False),
    sa.Column('parent_order_id', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('instrument_name', sa.String(length=256), nullable=True),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('filled_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['t212_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_t212_orders_api_key_id', 't212_orders', ['api_key_id'], unique=False)
    op.create_index('idx_t212_orders_date_created', 't212_orders', ['date_created'], unique=False)
    op.create_index('idx_t212_orders_t212_order_id', 't212_orders', ['t212_order_id'], unique=False)
    op.create_index('idx_t212_orders_ticker', 't212_orders', ['ticker'], unique=False)
    op.create_table('t212_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('t212_reference', sa.String(length=64), nullable=False),
    sa.Column('transaction_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['t212_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_t212_transactions_api_key_id', 't212_transactions', ['api_key_id'], unique=False)
    op.create_index('idx_t212_transactions_date_time', 't212_transactions', ['date_time'], unique=False)
    op.create_index('idx_t212_transactions_t212_reference', 't212_transactions', ['t212_reference'], unique=False)
    op.create_index('idx_t212_transactions_type', 't212_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_t212_transactions_type', table_name='t212_transactions')
    op.drop_index('idx_t212_transactions_t212_reference', table_name='t212_transactions')
    op.drop_index('idx_t212_transactions_date_time', table_name='t212_transactions')
    op.drop_index('idx_t212_transactions_api_key_id', table_name='t212_transactions')
    op.drop_table('t212_transactions')
    op.drop_index('idx_t212_orders_ticker', table_name='t212_orders')
    op.drop_index('idx_t212_orders_t212_order_id', table_name='t212_orders')
    op.drop_index('idx_t212_orders_date_created', table_name='t212_orders')
    op.drop_index('idx_t212_orders_api_key_id', table_name='t212_orders')
    op.drop_table('t212_orders')
    op.drop_index('idx_t212_dividends_ticker', table_name='t212_dividends')
    op.drop_index('idx_t212_dividends_t212_reference', table_name='t212_dividends')
    op.drop_index('idx_t212_dividends_paid_on', table_name='t212_dividends')
    op.drop_index('idx_t212_dividends_api_key_id', table_name='t212_dividends')
    op.drop_table('t212_dividends')
    # ### end Alembic commands ###
