"""add_standard_tags_fields

Revision ID: 0ce99eba4e62
Revises: 72b3ded8075b
Create Date: 2026-01-25 22:07:27.421837

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce99eba4e62'
down_revision: Union[str, Sequence[str], None] = '72b3ded8075b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add is_standard and is_hidden columns with server defaults for existing rows
    op.add_column('tags', sa.Column('is_standard', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tags', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_hidden')
    op.drop_column('tags', 'is_standard')
    # ### end Alembic commands ###
