"""add manual assets tables

Revision ID: 0d1c0abe3d33
Revises: e7e0862f0a29
Create Date: 2026-02-01 15:39:55.555514

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1c0abe3d33'
down_revision: Union[str, Sequence[str], None] = 'e7e0862f0a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('custom_type', sa.String(length=50), nullable=True),
    sa.Column('is_liability', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acquisition_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('value_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manual_assets_user_active', 'manual_assets', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_manual_assets_user_id', 'manual_assets', ['user_id'], unique=False)
    op.create_table('manual_asset_value_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['manual_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manual_asset_snapshots_asset_captured', 'manual_asset_value_snapshots', ['asset_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_manual_asset_snapshots_asset_captured', table_name='manual_asset_value_snapshots')
    op.drop_table('manual_asset_value_snapshots')
    op.drop_index('idx_manual_assets_user_id', table_name='manual_assets')
    op.drop_index('idx_manual_assets_user_active', table_name='manual_assets')
    op.drop_table('manual_assets')
    # ### end Alembic commands ###
