"""add_tags_tables

Revision ID: 1570934fc13b
Revises: 55b6582091bd
Create Date: 2026-01-24 22:57:14.002414

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1570934fc13b'
down_revision: Union[str, Sequence[str], None] = '55b6582091bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tags_user_id', 'tags', ['user_id'], unique=False)
    op.create_index('idx_tags_user_name', 'tags', ['user_id', 'name'], unique=True)
    op.create_table('transaction_tags',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )
    op.create_index('idx_transaction_tags_tag_id', 'transaction_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_tags_tag_id', table_name='transaction_tags')
    op.drop_table('transaction_tags')
    op.drop_index('idx_tags_user_name', table_name='tags')
    op.drop_index('idx_tags_user_id', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
