"""add balances

Revision ID: 28e8b4ad51ce
Revises: f8e1b1dd9feb
Create Date: 2025-12-01 22:17:56.724212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28e8b4ad51ce"
down_revision: Union[str, Sequence[str], None] = "f8e1b1dd9feb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("balance_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_currency", sa.String(length=3), nullable=False),
        sa.Column("balance_type", sa.String(length=50), nullable=False),
        sa.Column("credit_limit_included", sa.Boolean(), nullable=True),
        sa.Column("last_change_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bank_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("balances")
    # ### end Alembic commands ###
