"""add unified transactions table

Revision ID: 3649be6e9b64
Revises: 56636dc452a2
Create Date: 2026-01-24 19:12:09.195555

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3649be6e9b64'
down_revision: Union[str, Sequence[str], None] = '56636dc452a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=256), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('counterparty_name', sa.String(length=256), nullable=True),
    sa.Column('counterparty_account', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index('idx_transactions_account_provider_id', 'transactions', ['account_id', 'provider_id'], unique=True)
    op.create_index('idx_transactions_booking_date', 'transactions', ['booking_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_booking_date', table_name='transactions')
    op.drop_index('idx_transactions_account_provider_id', table_name='transactions')
    op.drop_index('idx_transactions_account_id', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
