"""init v3

Revision ID: 50caa30626e4
Revises: 78c333d567f6
Create Date: 2025-12-01 21:53:40.371449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50caa30626e4"
down_revision: Union[str, Sequence[str], None] = "78c333d567f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requisition_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("redirect", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=4), nullable=False),
        sa.Column("institution_id", sa.String(length=50), nullable=False),
        sa.Column("agreement", sa.String(length=36), nullable=False),
        sa.Column("reference", sa.String(length=36), nullable=False),
        sa.Column("link", sa.String(length=512), nullable=False),
        sa.Column("ssn", sa.String(length=64), nullable=True),
        sa.Column("account_selection", sa.Boolean(), nullable=False),
        sa.Column("redirect_immediate", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("bban", sa.String(length=128), nullable=True),
        sa.Column("bic", sa.String(length=128), nullable=True),
        sa.Column("cash_account_type", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("details", sa.String(length=512), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("iban", sa.String(length=200), nullable=True),
        sa.Column("linked_accounts", sa.String(length=128), nullable=True),
        sa.Column("msisdn", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("owner_address_unstructured", sa.String(length=256), nullable=True),
        sa.Column("owner_name", sa.String(length=256), nullable=True),
        sa.Column("product", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=7), nullable=True),
        sa.Column("scan", sa.String(length=14), nullable=True),
        sa.Column("usage", sa.String(length=4), nullable=True),
        sa.Column("requisition_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["requisition_id"],
            ["requisition_links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "balances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("balance_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_currency", sa.String(length=3), nullable=False),
        sa.Column("balance_type", sa.String(length=50), nullable=False),
        sa.Column("credit_limit_included", sa.Boolean(), nullable=True),
        sa.Column("last_change_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bank_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("booking_date", sa.DateTime(), nullable=True),
        sa.Column("booking_date_time", sa.DateTime(), nullable=True),
        sa.Column("value_date", sa.DateTime(), nullable=True),
        sa.Column("value_date_time", sa.DateTime(), nullable=True),
        sa.Column("transaction_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("transaction_currency", sa.String(length=3), nullable=False),
        sa.Column("creditor_name", sa.String(length=176), nullable=True),
        sa.Column("debtor_name", sa.String(length=176), nullable=True),
        sa.Column("end_to_end_id", sa.String(length=35), nullable=True),
        sa.Column("entry_reference", sa.String(length=128), nullable=True),
        sa.Column("additional_information", sa.String(length=512), nullable=True),
        sa.Column("additional_data_structured", sa.JSON(), nullable=True),
        sa.Column("balance_after", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bank_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("balances")
    op.drop_table("bank_accounts")
    op.drop_table("requisition_links")
    # ### end Alembic commands ###
