"""new column on link table for tracking account status

Revision ID: 6430569b9b91
Revises: c6954cadbc4f
Create Date: 2025-12-07 19:50:50.478737

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6430569b9b91"
down_revision: Union[str, Sequence[str], None] = "c6954cadbc4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gc_requisition_links", sa.Column("dg_account_expired", sa.Boolean(), nullable=True)
    )

    op.execute("UPDATE gc_requisition_links SET dg_account_expired = FALSE")

    op.alter_column(
        "gc_requisition_links", "dg_account_expired", existing_type=sa.Boolean(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gc_requisition_links", "dg_account_expired")
    # ### end Alembic commands ###
