"""add_transaction_splits_and_user_note

Revision ID: 6bc206b77d47
Revises: c088545ffdf6
Create Date: 2026-01-26 19:00:43.424747

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc206b77d47'
down_revision: Union[str, Sequence[str], None] = 'c088545ffdf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_splits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_splits_tag', 'transaction_splits', ['tag_id'], unique=False)
    op.create_index('idx_transaction_splits_transaction', 'transaction_splits', ['transaction_id'], unique=False)
    op.create_index('idx_transaction_splits_unique', 'transaction_splits', ['transaction_id', 'tag_id'], unique=True)
    op.add_column('transactions', sa.Column('user_note', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'user_note')
    op.drop_index('idx_transaction_splits_unique', table_name='transaction_splits')
    op.drop_index('idx_transaction_splits_transaction', table_name='transaction_splits')
    op.drop_index('idx_transaction_splits_tag', table_name='transaction_splits')
    op.drop_table('transaction_splits')
    # ### end Alembic commands ###
