"""adding friendly name field

Revision ID: 9f7b55f05a4f
Revises: 6430569b9b91
Create Date: 2025-12-07 20:51:18.043346

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f7b55f05a4f"
down_revision: Union[str, Sequence[str], None] = "6430569b9b91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gc_requisition_links", sa.Column("friendly_name", sa.String(length=128), nullable=True)
    )
    op.execute("UPDATE gc_requisition_links SET friendly_name = 'Missing Friendly Name'")

    op.alter_column("gc_requisition_links", "dg_account_expired", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gc_requisition_links", "friendly_name")
    # ### end Alembic commands ###
