"""add_tag_rules_table

Revision ID: c088545ffdf6
Revises: 0ce99eba4e62
Create Date: 2026-01-25 22:16:42.002375

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c088545ffdf6'
down_revision: Union[str, Sequence[str], None] = '0ce99eba4e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('merchant_contains', sa.String(length=200), nullable=True),
    sa.Column('merchant_exact', sa.String(length=200), nullable=True),
    sa.Column('description_contains', sa.String(length=200), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_not_contains', sa.String(length=200), nullable=True),
    sa.Column('description_not_contains', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tag_rules_user_id', 'tag_rules', ['user_id'], unique=False)
    op.create_index('idx_tag_rules_user_priority', 'tag_rules', ['user_id', 'priority'], unique=False)
    # Add is_auto with server default for existing rows
    op.add_column('transaction_tags', sa.Column('is_auto', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('transaction_tags', sa.Column('rule_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_transaction_tags_rule_id', 'transaction_tags', 'tag_rules', ['rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_tags_rule_id', 'transaction_tags', type_='foreignkey')
    op.drop_column('transaction_tags', 'rule_id')
    op.drop_column('transaction_tags', 'is_auto')
    op.drop_index('idx_tag_rules_user_priority', table_name='tag_rules')
    op.drop_index('idx_tag_rules_user_id', table_name='tag_rules')
    op.drop_table('tag_rules')
    # ### end Alembic commands ###
