"""add tag_id to recurring_patterns

Revision ID: cd45397c9071
Revises: 0d1c0abe3d33
Create Date: 2026-02-01 20:41:33.283197

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd45397c9071'
down_revision: Union[str, Sequence[str], None] = '0d1c0abe3d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_patterns', sa.Column('tag_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'recurring_patterns', 'tags', ['tag_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_patterns', type_='foreignkey')
    op.drop_column('recurring_patterns', 'tag_id')
    # ### end Alembic commands ###
