"""add balance_snapshots table

Revision ID: cdc71e9eb6d7
Revises: a946773cbd77
Create Date: 2026-01-30 18:18:57.227935

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc71e9eb6d7'
down_revision: Union[str, Sequence[str], None] = 'a946773cbd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_currency', sa.String(length=3), nullable=False),
    sa.Column('balance_type', sa.String(length=50), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unrealised_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_balance_snapshots_account_captured', 'balance_snapshots', ['account_id', 'captured_at'], unique=False)
    op.create_index('idx_balance_snapshots_captured_at', 'balance_snapshots', ['captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_balance_snapshots_captured_at', table_name='balance_snapshots')
    op.drop_index('idx_balance_snapshots_account_captured', table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    # ### end Alembic commands ###
