"""add direction to recurring_patterns

Revision ID: d0021699d9f2
Revises: cdc71e9eb6d7
Create Date: 2026-01-30 22:29:33.560514

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0021699d9f2'
down_revision: Union[str, Sequence[str], None] = 'cdc71e9eb6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add direction column with server default for existing records
    op.add_column(
        'recurring_patterns',
        sa.Column('direction', sa.String(length=20), nullable=False, server_default='expense')
    )
    # Remove server default after existing records are updated
    op.alter_column('recurring_patterns', 'direction', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_patterns', 'direction')
    # ### end Alembic commands ###
