"""Add lookup_hash to refresh_tokens

Revision ID: d8aca9a4c2ae
Revises: 1ef7aace8974
Create Date: 2026-01-25 10:43:29.121788

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8aca9a4c2ae'
down_revision: Union[str, Sequence[str], None] = '1ef7aace8974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Note: This migration deletes all existing refresh tokens because we can't
    backfill lookup_hash without the raw token values. Users will need to log
    in again after this migration.
    """
    # Delete all existing tokens - we can't backfill without raw values
    op.execute("DELETE FROM refresh_tokens")

    # Now add the NOT NULL column
    op.add_column('refresh_tokens', sa.Column('lookup_hash', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.create_index('idx_refresh_tokens_lookup_hash', 'refresh_tokens', ['lookup_hash'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['lookup_hash'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index('idx_refresh_tokens_lookup_hash', table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'lookup_hash')
    # ### end Alembic commands ###
