"""remove deleted table

Revision ID: ddd49c1cf114
Revises: 88fa944cb564
Create Date: 2025-12-01 22:13:24.283147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddd49c1cf114"
down_revision: Union[str, Sequence[str], None] = "88fa944cb564"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("balances")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balances",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "balance_amount", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False
        ),
        sa.Column("balance_currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
        sa.Column("balance_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("credit_limit_included", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("last_change_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["bank_accounts.id"], name=op.f("balances_account_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("balances_pkey")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("booking_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("booking_date_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("value_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("value_date_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "transaction_currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
        sa.Column("creditor_name", sa.VARCHAR(length=176), autoincrement=False, nullable=True),
        sa.Column("debtor_name", sa.VARCHAR(length=176), autoincrement=False, nullable=True),
        sa.Column("end_to_end_id", sa.VARCHAR(length=35), autoincrement=False, nullable=True),
        sa.Column("entry_reference", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column(
            "additional_information", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
        sa.Column(
            "additional_data_structured",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "balance_after",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["bank_accounts.id"], name=op.f("transactions_account_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transactions_pkey")),
    )
    # ### end Alembic commands ###
