name: dbt_project
version: "1.0"
profile: duckdb_local

on-run-start:
  - "INSTALL postgres; LOAD postgres;"
  # Default values allow dbt parse at build time; real env vars used at runtime
  - |
    ATTACH 'postgresql://{{ env_var("POSTGRES_USERNAME", "build") }}:{{ env_var("POSTGRES_PASSWORD", "build") }}@{{ env_var("POSTGRES_HOSTNAME", "localhost") }}:{{ env_var("POSTGRES_PORT", "5432") }}/{{ env_var("POSTGRES_DATABASE", "build") }}' AS pg (TYPE POSTGRES, READ_ONLY);

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
log-path: "logs"
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "logs"
  - "dbt_packages"

models:
  dbt_project:
    +materialized: view

    1_source:
      +materialized: table  # Tables (not views) so data is in DuckDB for API queries
      +schema: source
      +tags: ["auto_eager"]
      unified:
        +meta:
          dagster:
            group: dbt_source_unified
      gocardless:
        +meta:
          dagster:
            group: dbt_source_gocardless

    2_staging:
      +schema: staging
      +meta:
        dagster:
          group: dbt_staging
      +tags: ["auto_eager"]

    3_mart:
      +schema: mart
      +meta:
        dagster:
          group: dbt_mart
      +tags: ["auto_eager", "auto_hourly"]
