name: dbt_project
version: "1.0"
profile: duckdb_local

on-run-start:
  - "INSTALL postgres; LOAD postgres;"
  - |
    ATTACH 'postgresql://{{ env_var("POSTGRES_USERNAME") }}:{{ env_var("POSTGRES_PASSWORD") }}@{{ env_var("POSTGRES_HOSTNAME") }}:{{ env_var("POSTGRES_PORT") }}/{{ env_var("POSTGRES_DATABASE") }}' AS pg (TYPE POSTGRES, READ_ONLY);

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
log-path: "logs"
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "logs"
  - "dbt_packages"

models:
  dbt_project:
    +materialized: view

    1_source:
      +materialized: table
      +schema: source
      +meta:
        dagster:
          group: dbt_source
      +tags: ["auto_eager"]

    2_staging:
      +schema: staging
      +meta:
        dagster:
          group: dbt_staging
      +tags: ["auto_eager"]

    3_mart:
      +schema: mart
      +meta:
        dagster:
          group: dbt_mart
      +tags: ["auto_eager", "auto_hourly"]
