duckdb_local:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '../data/analytics.duckdb') }}"
      schema: main
      threads: 4
      extensions:
        - postgres
      external_root: "{{ env_var('PARQUET_DIR', '../data/parquet') }}/mart"
