-- Staging layer for GoCardless transactions
-- Transforms source data into analytics-ready format

WITH SOURCE AS (
    SELECT * FROM {{ ref('src_gocardless_transactions') }}
)

SELECT
    TRANSACTION_ID,
    ACCOUNT_ID,
    STATUS                 AS TRANSACTION_TYPE,  -- 'booked' or 'pending'
    BOOKING_DATE,
    VALUE_DATE,
    BOOKING_DATETIME,
    NULL::TIMESTAMP        AS VALUE_DATETIME,  -- Not available in current source
    TRANSACTION_AMOUNT,
    CURRENCY               AS TRANSACTION_AMOUNT_CURRENCY,
    DEBTOR_ACCOUNT,
    REMITTANCE_INFORMATION AS REMITTANCE_INFORMATION_UNSTRUCTURED,
    PROPRIETARY_BANK_CODE  AS PROPRIETARY_BANK_TRANSACTION_CODE,
    INTERNAL_TRANSACTION_ID,
    NULL::VARCHAR          AS ENTRY_REFERENCE,  -- Not available in current source
    CREDITOR_NAME,
    DEBTOR_NAME,
    NULL::VARCHAR          AS ADDITIONAL_INFORMATION,  -- Not available in current source
    CREDITOR_ACCOUNT,
    NULL::DECIMAL          AS CURRENCY_EXCHANGE_INSTRUCTED_AMOUNT,
    NULL::VARCHAR          AS CURRENCY_EXCHANGE_INSTRUCTED_AMOUNT_CURRENCY,
    NULL::VARCHAR          AS CURRENCY_EXCHANGE_SOURCE_CURRENCY,
    NULL::DECIMAL          AS CURRENCY_EXCHANGE_RATE,
    EXTRACTED_AT           AS LAST_UPDATED,
    EXTRACTED_AT::DATE     AS _EXTRACT_DT
FROM SOURCE
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID, ACCOUNT_ID ORDER BY EXTRACTED_AT DESC) = 1
